name: typescript

# Run this workflow every time a new commit pushed to your repository
on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  ts-test:
    name: typescript unit test
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - run: DEBIAN_FRONTEND="noninteractive" sudo apt update -qq && sudo apt install nodejs npm yarn
      - run: DEBIAN_FRONTEND="noninteractive" sudo npm install -g typescript
      - run: |
          yarn install
          yarn compile
          yarn run package
          yarn run vsce
      - name: releaseFile
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            *.vsix
          
